server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/supunsithmal/spring-cloud-config-store
          search-paths:
           - '*service'

member:
 rent:
  min: 7
  max: 30
